const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const state={image:null,expenses:JSON.parse(localStorage.getItem('clearcost-expenses')||'[]')};
const form=$('#expenseForm'), fileInput=$('#fileInput'), dropzone=$('#dropzone');
const keyModal=$('#keyModal'), keyButton=$('#apiKeyBtn');

async function refreshKeyStatus(){try{const r=await fetch('/api/config/status');const data=await r.json();keyButton.classList.toggle('connected',data.connected);keyButton.lastChild.textContent=data.connected?' API 연결됨':' API 키 연결'}catch{}}
keyButton.addEventListener('click',()=>{keyModal.classList.remove('hidden');setTimeout(()=>$('#apiKeyInput').focus(),50)});
$('#closeKeyModal').addEventListener('click',()=>keyModal.classList.add('hidden'));
keyModal.addEventListener('click',e=>{if(e.target===keyModal)keyModal.classList.add('hidden')});
$('#keyForm').addEventListener('submit',async e=>{e.preventDefault();const input=$('#apiKeyInput'),message=$('#keyMessage'),button=e.submitter;button.disabled=true;message.textContent='연결을 확인하고 있어요...';try{const r=await fetch('/api/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({apiKey:input.value})});const data=await r.json();if(!r.ok)throw new Error(data.error||'연결하지 못했습니다.');input.value='';message.style.color='var(--green)';message.textContent='연결되었습니다.';await refreshKeyStatus();setTimeout(()=>keyModal.classList.add('hidden'),600)}catch(error){message.style.color='var(--danger)';message.textContent=error.message}finally{button.disabled=false}});
refreshKeyStatus();

function setView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===id));if(id!=='register')renderLists();window.scrollTo({top:0,behavior:'smooth'})}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>setView(b.dataset.view)));

function loadImage(file){if(!file||!file.type.startsWith('image/'))return alert('이미지 파일을 선택해주세요.');if(file.size>10*1024*1024)return alert('10MB 이하 이미지를 선택해주세요.');const reader=new FileReader();reader.onload=()=>{state.image=reader.result;$('#preview').src=state.image;$('#preview').style.display='block';$('#dropPrompt').classList.add('hidden');$('#recognizeBtn').disabled=false;$('#changeBtn').classList.remove('hidden');$('#imageBadge').textContent='업로드 완료';$('#imageBadge').classList.remove('muted')};reader.readAsDataURL(file)}
fileInput.addEventListener('change',e=>loadImage(e.target.files[0]));
['dragenter','dragover'].forEach(e=>dropzone.addEventListener(e,x=>{x.preventDefault();dropzone.classList.add('drag')}));
['dragleave','drop'].forEach(e=>dropzone.addEventListener(e,x=>{x.preventDefault();dropzone.classList.remove('drag')}));
dropzone.addEventListener('drop',e=>loadImage(e.dataTransfer.files[0]));
$('#changeBtn').addEventListener('click',()=>fileInput.click());

$('#recognizeBtn').addEventListener('click',async()=>{const btn=$('#recognizeBtn');btn.disabled=true;btn.innerHTML='<span>◌</span> 원본 해상도로 정밀 분석 중...';$('#resultBadge').textContent='인식 중';try{const response=await fetch('/api/recognize-receipt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({imageBase64:state.image})});const result=await response.json();if(!response.ok)throw new Error(result.error||'AI 인식에 실패했습니다.');const values=result.extracted||{};Object.entries(values).forEach(([k,v])=>{if(form.elements[k]&&v!==null)form.elements[k].value=v});if(!values.amount&&values.taxableAmount!==null&&values.vat!==null)form.elements.amount.value=Number(values.taxableAmount)+Number(values.vat);Object.entries(result.confidence||{}).forEach(([k,v])=>{const el=document.querySelector(`[data-confidence="${k}"]`);if(el){el.className=`confidence ${v}`;el.textContent={high:'높음',medium:'보통',low:'낮음'}[v]||'확인 필요'}});$('#warning').textContent=(result.warnings||[]).join(' · ')||'AI가 모든 필드를 높은 신뢰도로 인식했습니다.';$('#emptyState').classList.add('hidden');form.classList.remove('hidden');$('#resultBadge').textContent='AI 인식 완료';$('#resultBadge').classList.remove('muted');btn.innerHTML='<span>✓</span> 다시 인식하기';form.scrollIntoView({behavior:'smooth',block:'start'})}catch(error){$('#resultBadge').textContent='인식 실패';$('#resultBadge').classList.add('muted');btn.innerHTML='<span>↻</span> 다시 시도하기';alert(error.message)}finally{btn.disabled=false}});

form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const data=Object.fromEntries(new FormData(form));data.amount=Number(data.amount);data.vat=Number(data.vat||0);data.settlementIncluded=form.elements.settlementIncluded.checked;data.id='EXP-'+Date.now();data.image=state.image;data.createdAt=new Date().toISOString();state.expenses.unshift(data);localStorage.setItem('clearcost-expenses',JSON.stringify(state.expenses));$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2800);setTimeout(()=>setView('settlement'),650)});

function renderLists(){const included=state.expenses.filter(x=>x.settlementIncluded);$('#totalAmount').textContent=included.reduce((s,x)=>s+x.amount,0).toLocaleString('ko-KR')+'원';$('#settlementRows').innerHTML=included.map(x=>`<tr><td>${x.paidDate}</td><td><strong>${x.project}</strong><br><span>${x.artist}</span></td><td>${x.merchant}</td><td>${x.category}</td><td>${x.purpose}</td><td class="right"><strong>${x.amount.toLocaleString('ko-KR')}원</strong></td><td><span class="status">정산 반영 가능</span></td></tr>`).join('');$('#settlementEmpty').classList.toggle('hidden',included.length>0);$('#archiveGrid').innerHTML=state.expenses.map(x=>`<article class="archive-card"><img src="${x.image}" alt="${x.merchant} 영수증"><div class="archive-info"><strong>${x.merchant}</strong><span>${x.paidDate} · ${x.amount.toLocaleString('ko-KR')}원 · ${x.artist}</span></div></article>`).join('');$('#archiveEmpty').classList.toggle('hidden',state.expenses.length>0)}
renderLists();
